version: 0.2

phases:
  install:
    commands:
      - echo run install on `date`
      - apt-get update
      - apt-get install -y zip
  pre_build:
    commands:
      - echo run unittests on `date`
      - make test
      # output all env vars
      #- printenv
  build:
    commands:
      - echo Build started on `date`
      - make LIBS='bottle' LIB_DIR="$PWD/build/lib.linux-x86_64-2.7" build dist

artifacts:
  files:
    # infra.
    - cd/cf-vpc.yaml
    - cd/cf-vpc-dev-configs.json
    # for ec2
    - dist/aws-cicd-0.1.0.tar.gz
    - cd/cf-ec2.yaml
    - cd/cf-ec2-dev-configs.json

