version: 0.2

phases:
  install:
    commands:
      - echo run install on `date`
      - apt-get update
      - apt-get install -y zip
  pre_build:
    commands:
      - echo run unittests on `date`
      - make test
      # output all env vars
      #- printenv
  build:
    commands:
      - echo Build started on `date`
      - make LIBS='bottle' build dist
  post_build:
    commands:
      - echo Build completed on `date`
      # for api gateway
      # generate a packaged-cf-sl.yaml for deployment later
      - >
        aws cloudformation package --template-file cd/cf-sl.yaml
        --s3-bucket ${ARTIFACTS_BUCKET_NAME} --s3-prefix ${ARTIFACTS_OBJECT_KEY}
        --output-template-file cd/packaged-cf-sl.yaml
      # for dcoker image
      # push to ecr
      - $(aws ecr get-login --no-include-email)
      - aws ecr describe-repositories --repository-names $ECR_REPO_NAME --query repositories[0].repositoryUri --output text > /tmp/ecr_repo.txt
      - docker tag aws-cicd:0.1.0 $(cat /tmp/ecr_repo.txt):0.1.0
      - docker push $(cat /tmp/ecr_repo.txt):0.1.0
      - docker tag aws-cicd:latest $(cat /tmp/ecr_repo.txt):latest
      - docker push $(cat /tmp/ecr_repo.txt):latest

artifacts:
  files:
    # for ec2
    - dist/aws-cicd-0.1.0.tar.gz
    - cd/cf-vpc.yaml
    - cd/cf-vpc-dev-configs.json
    - cd/cf-ec2.yaml
    - cd/cf-ec2-dev-configs.json
    # for api gateway
    - dist/api_sleep-0.1.0.zip
    - dist/api_secret-0.1.0.zip
    - dist/api_home-0.1.0.zip
    - dist/api_healthcheck-0.1.0.zip
    - cd/packaged-cf-sl.yaml

